FROM ubuntu:artful
MAINTAINER Jermine.hu@qq.com
RUN apt-get update -y && apt-get install -y --no-install-recommends python3 python3-pip ;\
    pip3 install --upgrade pip ;\
    python3 -V && pip3 -V ;\
    pip3 --no-cache-dir install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.5.0-cp36-cp36m-linux_x86_64.whl ;\
    apt-get autoremove && apt-get autoclean ;\
    rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
