FROM  jermine/dl:cpu.opencv
MAINTAINER Jermine.hu@qq.com
ENV PYTORCH_VERSION 0.3.1
RUN apt-get update -y && apt-get install -y python3 python3-pip ;\
    pip3 install --upgrade pip ;\
    python3 -V && pip3 -V ;\
    pip3 install --no-cache-dir http://download.pytorch.org/whl/cpu/torch-${PYTORCH_VERSION}-cp36-cp36m-linux_x86_64.whl   ;\
    pip3 install --no-cache-dir torchvision ;\
    apt-get autoremove && apt-get autoclean