FROM  jermine/dl:gpu.opencv
MAINTAINER Jermine.hu@qq.com
ENV MXNET_VERSION cu91
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3 python3-pip graphviz ;\
    pip3 install --upgrade pip==9.0.3 ;\
    python3 -V && pip3 -V ;\
    pip3 --no-cache-dir install mxnet-${MXNET_VERSION} graphviz ;\
    apt-get autoremove && apt-get autoclean ;\
    rm -rf /var/lib/apt/lists/*
